### ISSUE TITLE
Compatability with NXG 3.0

### ISSUE THREAD

**Issue by AliFlux** [ni/nidevlabs#12]
Hi.

The current examples aren't compatible with the latest version of NXG. The repo was updated about 2 years ago; is there a plan to maintain this repository, or the NXG project as a whole?

Thanks.

**Comment by ccifra** [comment]
We regularly update the repo to maintain compatibility with the latest betas and releases.  The repo was last updated to support the current beta of NXG.  We are also actively adding more examples.

You can see that we have had several Commits recently:
https://github.com/ni/nidevlabs/commits/master

Commit 785c9e0bb3f339761907d8f53504cc5ad6f9a0fc brought the repo up to date with 3.0.
https://github.com/ni/nidevlabs/commit/34336543cb94245bb5a991b81bec3d0b4095de35

If you have access to the NXG betas you can use those for this repo.  I can also help you create a branch that matches 3.0.
