### ISSUE TITLE
Using FanEditorExtensions in NXG

### ISSUE THREAD

**Issue by tholsan** [ni/nidevlabs#4]
I have built FanEditorExtensions, but how do I use it in LabVIEW? I can find no documentation of it.

**Comment by ccifra** [comment]
We have updated the examples to be compatible with the NXG 2.0 Beta.  If you install the beta the examples should work correctly.  Building the examples will copy output into the addons location for NXG.  You should be able to launch the app and see the example fan control in the palette.
